import type { Course, Phrase } from "./schema.ts";

const reviewStatus = {
  linguistic: "required",
  mexicanUsage: "required",
  safety: "not-applicable",
} as const;
const intervals = [0, 1, 3, 7, 14, 30] as const;

function phrase(
  id: string,
  esMX: string,
  english: string,
  pronunciationAid: string,
  context: string,
  requiredConcepts: string[],
  conceptAliases: Record<string, string[]>,
  acceptedAnswers: string[] = [esMX],
  likelyReplies: { esMX: string; english: string }[] = [],
  register: Phrase["register"] = "neutral",
): Phrase {
  const slug = id.replaceAll(".", "-");
  return {
    id,
    esMX,
    english,
    pronunciationAid,
    context,
    register,
    productive: true,
    acceptedAnswers,
    requiredConcepts,
    conceptAliases,
    criticalConcepts: [],
    criticalTerms: {},
    optionalWords: ["yo"],
    likelyReplies,
    commonErrors: [],
    audio: {
      normal: {
        src: `/audio/generated/${slug}.normal.mp3`,
        assetId: `${id}.normal.2026.1`,
        voiceSlot: "primary",
        speed: "normal",
        productionReady: true,
      },
      slow: {
        src: `/audio/generated/${slug}.slow.mp3`,
        assetId: `${id}.slow.2026.1`,
        voiceSlot: "secondary",
        speed: "slow",
        productionReady: true,
      },
    },
    reviewIntervalsDays: [...intervals],
    offline: "core",
    reviewStatus,
  };
}

export const phrases: Phrase[] = [
  phrase(
    "mx.greeting.hola",
    "Hola",
    "Hello",
    "OH-lah",
    "Works throughout the day in almost any friendly interaction.",
    ["greeting"],
    { greeting: ["hola"] },
  ),
  phrase(
    "mx.greeting.buenos_dias",
    "Buenos días",
    "Good morning",
    "BWEH-nos DEE-as",
    "Use from morning until around midday.",
    ["morning-greeting"],
    { "morning-greeting": ["buenos dias", "buen día"] },
    ["Buenos días", "Buen día"],
  ),
  phrase(
    "mx.polite.gracias",
    "Gracias",
    "Thank you",
    "GRAH-syahs",
    "A high-value way to close almost every exchange warmly.",
    ["thanks"],
    { thanks: ["gracias", "muchas gracias"] },
    ["Gracias", "Muchas gracias"],
    [{ esMX: "De nada.", english: "You’re welcome." }],
  ),
  phrase(
    "mx.polite.please",
    "Por favor",
    "Please",
    "por fah-BOR",
    "Add it to requests to sound polite.",
    ["please"],
    { please: ["por favor"] },
  ),
  phrase(
    "mx.polite.you_are_welcome",
    "De nada",
    "You’re welcome",
    "deh NAH-dah",
    "The most common short response to thanks.",
    ["welcome"],
    { welcome: ["de nada", "no hay de que"] },
    ["De nada", "No hay de qué"],
  ),
  phrase(
    "mx.polite.excuse_pass",
    "Con permiso",
    "Excuse me / may I pass",
    "kohn pehr-MEE-soh",
    "Use when passing through a crowd or entering someone’s space.",
    ["permission"],
    { permission: ["con permiso", "permiso"] },
    ["Con permiso", "Permiso"],
  ),
  phrase(
    "mx.intro.my_name",
    "Me llamo…",
    "My name is…",
    "meh YAH-moh",
    "Complete the phrase with your name.",
    ["name-introduction"],
    { "name-introduction": ["me llamo", "mi nombre es", "soy"] },
    ["Me llamo", "Mi nombre es", "Soy"],
    [{ esMX: "Mucho gusto.", english: "Nice to meet you." }],
    "friendly-neutral",
  ),
  phrase(
    "mx.intro.nice_to_meet",
    "Mucho gusto",
    "Nice to meet you",
    "MOO-choh GOOS-toh",
    "A warm, neutral response after learning someone’s name.",
    ["nice-to-meet"],
    { "nice-to-meet": ["mucho gusto", "encantado", "encantada"] },
    ["Mucho gusto", "Encantado", "Encantada"],
    [],
    "friendly-neutral",
  ),
  phrase(
    "mx.intro.your_name",
    "¿Cómo se llama?",
    "What is your name?",
    "KOH-moh seh YAH-mah",
    "Polite formal-default wording for an adult stranger.",
    ["ask-name"],
    { "ask-name": ["como se llama", "cual es su nombre"] },
    ["¿Cómo se llama?", "¿Cuál es su nombre?"],
    [{ esMX: "Me llamo Ana.", english: "My name is Ana." }],
    "formal-neutral",
  ),
  phrase(
    "mx.origin.we_sa",
    "Somos de Sudáfrica",
    "We are from South Africa",
    "SOH-mohs deh sood-AH-free-kah",
    "Use when speaking for both travellers.",
    ["we", "south-africa"],
    { we: ["somos", "venimos"], "south-africa": ["sudafrica"] },
    ["Somos de Sudáfrica", "Venimos de Sudáfrica"],
  ),
  phrase(
    "mx.origin.i_sa",
    "Soy de Sudáfrica",
    "I am from South Africa",
    "soy deh sood-AH-free-kah",
    "Use when introducing only yourself.",
    ["i-am-from", "south-africa"],
    { "i-am-from": ["soy de", "vengo de"], "south-africa": ["sudafrica"] },
    ["Soy de Sudáfrica", "Vengo de Sudáfrica"],
  ),
  phrase(
    "mx.language.little",
    "Hablo un poco de español",
    "I speak a little Spanish",
    "AH-bloh oon POH-koh deh ehs-pah-NYOL",
    "Sets helpful expectations without ending the conversation.",
    ["speak", "little", "spanish"],
    { speak: ["hablo"], little: ["un poco", "poquito"], spanish: ["espanol"] },
    ["Hablo un poco de español", "Hablo poquito español"],
    [{ esMX: "¡Muy bien!", english: "Very good!" }],
  ),
  phrase(
    "mx.language.not_much",
    "No hablo mucho español",
    "I don’t speak much Spanish",
    "noh AH-bloh MOO-choh ehs-pah-NYOL",
    "A clear, polite limit. The word no changes the meaning and is protected.",
    ["negation", "speak", "spanish"],
    { negation: ["no"], speak: ["hablo"], spanish: ["espanol"] },
    ["No hablo mucho español", "No hablo muy bien español"],
    [{ esMX: "No se preocupe.", english: "Don’t worry." }],
  ),
  phrase(
    "mx.repair.slower_full",
    "¿Puede hablar más despacio?",
    "Can you speak more slowly?",
    "PWEH-deh ah-BLAR mahs deh-SPAH-syoh",
    "Polite formal-default request when speech is too fast.",
    ["speak", "slower"],
    { speak: ["hablar", "hable"], slower: ["mas despacio", "mas lento"] },
    [
      "¿Puede hablar más despacio?",
      "¿Podría hablar más despacio?",
      "¿Puede hablar más lento?",
    ],
    [{ esMX: "Sí, claro.", english: "Yes, of course." }],
    "formal-neutral",
  ),
  phrase(
    "mx.repair.slower_short",
    "Más despacio, por favor",
    "More slowly, please",
    "mahs deh-SPAH-syoh por fah-BOR",
    "A short repair phrase when the full question is hard to retrieve.",
    ["slower"],
    { slower: ["mas despacio", "mas lento"] },
    ["Más despacio, por favor", "Más lento, por favor", "Más despacio"],
    [{ esMX: "Claro.", english: "Of course." }],
  ),
];

const protectedNegation = phrases.find(
  (item) => item.id === "mx.language.not_much",
);
if (protectedNegation) {
  protectedNegation.criticalConcepts = ["negation"];
  protectedNegation.criticalTerms = { negation: ["no"] };
}

function orderedListenChoices(ids: string[], day: number) {
  const choices = ids.map((id) => phrases.find((p) => p.id === id)!.english);
  const answer = choices[0]!;
  const distractors = choices.slice(1);
  const answerPosition = (day + 2) % choices.length;
  return [
    ...distractors.slice(0, answerPosition),
    answer,
    ...distractors.slice(answerPosition),
  ];
}

const normalLesson = (
  day: number,
  date: string,
  title: string,
  outcome: string,
  ids: string[],
  reviews: string[],
  scenario: string,
) => ({
  id: `mx71.d${String(day).padStart(2, "0")}`,
  day,
  date,
  title,
  outcome,
  estimatedMinutes: 7,
  newPhraseIds: ids,
  reviewPhraseIds: reviews,
  exercises: [
    { id: `d${day}.review`, type: "due-review" as const, limit: 3 },
    ...ids.flatMap((phraseId, index) => [
      { id: `d${day}.present.${index}`, type: "present" as const, phraseId },
      {
        id: `d${day}.retrieve.${index}`,
        type: "retrieve" as const,
        phraseId,
        prompt: "Recall the Spanish phrase before revealing it.",
      },
    ]),
    {
      id: `d${day}.listen`,
      type: "listen-choice" as const,
      phraseId: ids[0]!,
      options: orderedListenChoices(ids, day),
      answer: phrases.find((p) => p.id === ids[0])!.english,
    },
    {
      id: `d${day}.speak`,
      type: "speak" as const,
      phraseId: ids[0]!,
      prompt: phrases.find((p) => p.id === ids[0])!.english,
    },
    {
      id: `d${day}.scenario`,
      type: "micro-scenario" as const,
      prompt: scenario,
      phraseIds: ids,
    },
  ],
  completionMessage: outcome,
  travelPoints: 10,
  category: "foundations" as const,
  reviewStatus,
});

export const course: Course = {
  id: "mx-travel-71",
  version: "2026.1",
  title: "Rumbo: Mexico-ready Spanish",
  teachingLanguage: "en",
  targetLocale: "es-MX",
  startDate: "2026-08-10",
  departureDate: "2026-10-20",
  phase: {
    id: "foundations",
    title: "Foundations and repair",
    dayRange: [1, 7],
  },
  phrases,
  lessons: [
    normalLesson(
      1,
      "2026-08-10",
      "First words",
      "You can greet someone and close with thanks.",
      ["mx.greeting.hola", "mx.greeting.buenos_dias", "mx.polite.gracias"],
      [],
      "You enter a small hotel in the morning. Greet the host and thank them.",
    ),
    normalLesson(
      2,
      "2026-08-11",
      "Politeness that travels",
      "You can make a request and move through a space politely.",
      [
        "mx.polite.please",
        "mx.polite.you_are_welcome",
        "mx.polite.excuse_pass",
      ],
      ["mx.greeting.hola", "mx.polite.gracias"],
      "You need to pass through a busy café. Ask to pass, then respond to thanks.",
    ),
    normalLesson(
      3,
      "2026-08-12",
      "Introduce yourself",
      "You can exchange names politely.",
      ["mx.intro.my_name", "mx.intro.nice_to_meet", "mx.intro.your_name"],
      ["mx.greeting.buenos_dias", "mx.polite.gracias"],
      "A host greets you. Say your name, ask theirs, and respond warmly.",
    ),
    normalLesson(
      4,
      "2026-08-13",
      "Say where you’re from",
      "You can say that you are from South Africa.",
      ["mx.origin.we_sa", "mx.origin.i_sa"],
      ["mx.intro.my_name", "mx.intro.nice_to_meet"],
      "A local asks where you are from. Answer for yourself, then for both travellers.",
    ),
    normalLesson(
      5,
      "2026-08-14",
      "Set expectations",
      "You can explain that you speak only a little Spanish.",
      ["mx.language.little", "mx.language.not_much"],
      ["mx.origin.we_sa", "mx.polite.please"],
      "Someone begins speaking Spanish. Explain your level, then keep the interaction friendly.",
    ),
    normalLesson(
      6,
      "2026-08-15",
      "Slow things down",
      "You can ask someone to speak more slowly without giving up.",
      ["mx.repair.slower_full", "mx.repair.slower_short"],
      ["mx.language.little", "mx.polite.gracias"],
      "A shopkeeper speaks quickly. Ask them politely to slow down and thank them.",
    ),
    {
      id: "mx71.d07",
      day: 7,
      date: "2026-08-16",
      title: "Mexico Mission: Friendly arrival",
      outcome: "Combine your first week in one friendly arrival.",
      estimatedMinutes: 8,
      newPhraseIds: [],
      reviewPhraseIds: [
        "mx.greeting.hola",
        "mx.intro.my_name",
        "mx.origin.we_sa",
        "mx.language.little",
        "mx.repair.slower_short",
        "mx.polite.gracias",
      ],
      exercises: [
        { id: "d7.review", type: "due-review", limit: 5 },
        {
          id: "d7.scenario",
          type: "micro-scenario",
          prompt: "Complete the Friendly arrival mission.",
          phraseIds: [
            "mx.greeting.hola",
            "mx.intro.my_name",
            "mx.origin.we_sa",
            "mx.language.little",
            "mx.repair.slower_short",
            "mx.polite.gracias",
          ],
        },
      ],
      completionMessage: "You can handle a short, friendly arrival in Spanish.",
      travelPoints: 25,
      category: "foundations",
      reviewStatus,
    },
  ],
  scenarios: [
    {
      id: "mx.mission.friendly-arrival.v1",
      version: "1.0.0",
      title: "Friendly arrival",
      goal: "Greet a host, introduce yourself, share your origin and language level, ask for slower speech, then close with thanks.",
      startTurnId: "host-welcome",
      successTurnIds: ["host-close"],
      requiredIntents: [
        "greet",
        "name",
        "origin",
        "limited-spanish",
        "slower",
        "thanks",
      ],
      reviewStatus,
      turns: [
        {
          id: "host-welcome",
          speaker: "host",
          line: "¡Buenos días! Bienvenidos.",
          meaning: "Good morning! Welcome.",
          acceptedPhraseIds: [],
          next: "learner-greet",
        },
        {
          id: "learner-greet",
          speaker: "learner",
          line: "Your turn",
          meaning: "Greet the host.",
          expectedIntent: "greet",
          acceptedPhraseIds: ["mx.greeting.hola", "mx.greeting.buenos_dias"],
          hint: "Try Hola or Buenos días.",
          repair: "Start with: Hola…",
          next: "host-name",
        },
        {
          id: "host-name",
          speaker: "host",
          line: "¿Cómo se llama?",
          meaning: "What is your name?",
          acceptedPhraseIds: [],
          next: "learner-name",
        },
        {
          id: "learner-name",
          speaker: "learner",
          line: "Your turn",
          meaning: "Say your name.",
          expectedIntent: "name",
          acceptedPhraseIds: ["mx.intro.my_name"],
          hint: "Start with Me llamo…",
          repair: "Say: Me llamo, then your name.",
          next: "host-origin",
        },
        {
          id: "host-origin",
          speaker: "host",
          line: "¿De dónde son?",
          meaning: "Where are you from?",
          acceptedPhraseIds: [],
          next: "learner-origin",
        },
        {
          id: "learner-origin",
          speaker: "learner",
          line: "Your turn",
          meaning: "Say you are from South Africa.",
          expectedIntent: "origin",
          acceptedPhraseIds: ["mx.origin.we_sa", "mx.origin.i_sa"],
          hint: "Sudáfrica is South Africa.",
          repair: "Try: Somos de Sudáfrica.",
          next: "host-fast",
        },
        {
          id: "host-fast",
          speaker: "host",
          line: "¡Qué gusto! ¿Es su primera vez aquí en México?",
          meaning: "Nice! Is this your first time here in Mexico?",
          acceptedPhraseIds: [],
          next: "learner-limited",
        },
        {
          id: "learner-limited",
          speaker: "learner",
          line: "Your turn",
          meaning: "Explain that you speak little Spanish.",
          expectedIntent: "limited-spanish",
          acceptedPhraseIds: ["mx.language.little", "mx.language.not_much"],
          hint: "Start with Hablo… or No hablo…",
          repair: "Try: Hablo un poco de español.",
          next: "host-fast-2",
        },
        {
          id: "host-fast-2",
          speaker: "host",
          line: "Claro, tenemos muchas recomendaciones para ustedes.",
          meaning: "Of course, we have many recommendations for you.",
          acceptedPhraseIds: [],
          next: "learner-slower",
        },
        {
          id: "learner-slower",
          speaker: "learner",
          line: "Your turn",
          meaning: "Ask the host to slow down.",
          expectedIntent: "slower",
          acceptedPhraseIds: [
            "mx.repair.slower_full",
            "mx.repair.slower_short",
          ],
          hint: "Use más despacio.",
          repair: "Try: Más despacio, por favor.",
          next: "host-agrees",
        },
        {
          id: "host-agrees",
          speaker: "host",
          line: "Sí, claro.",
          meaning: "Yes, of course.",
          acceptedPhraseIds: [],
          next: "learner-thanks",
        },
        {
          id: "learner-thanks",
          speaker: "learner",
          line: "Your turn",
          meaning: "Close with thanks.",
          expectedIntent: "thanks",
          acceptedPhraseIds: ["mx.polite.gracias"],
          hint: "One word closes this warmly.",
          repair: "Say: Gracias.",
          next: "host-close",
        },
        {
          id: "host-close",
          speaker: "host",
          line: "De nada. ¡Que disfruten México!",
          meaning: "You’re welcome. Enjoy Mexico!",
          acceptedPhraseIds: [],
          next: null,
        },
      ],
    },
  ],
};

export const phraseById = new Map(
  course.phrases.map((item) => [item.id, item]),
);
export const lessonById = new Map(
  course.lessons.map((item) => [item.id, item]),
);
